apiVersion: v1
kind: Pod
metadata:
  name: gireesh-login
spec:
  containers:
  - name: vol-container
    image: gitlab-registry.nautilus.optiputer.net/yol070/research-containers/research-login-v2
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        memory: "8Gi"
        cpu: 2
      limits:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: 2
    volumeMounts:
    - name: gireesh-volume     #use your own volune path
      mountPath: /gireesh-volume
  restartPolicy: Never
  volumes:
    - name: gireesh-volume
      persistentVolumeClaim:
        claimName: gireesh-volume
